# Generated by Django 5.0.6 on 2024-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='img',
        ),
        migrations.AddField(
            model_name='livro',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livros'),
        ),
    ]
