# Generated by Django 5.0.6 on 2024-05-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_livro_img_livro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='image',
            field=models.ImageField(default='', upload_to='capa_livros'),
        ),
    ]
